fix(parallel_names): first fix of bug
Dessia-tech/plot_data pull request #265
Opened 2023-06-05 15:57 UTC by Tanguylo

2023-06-09 10:44 UTC, Tanguylo commented
Auto adapt fontsize considering available space in a 2D bounding box.
Can still be improved by adding a small but complicated algorithm that i think is not required for the moment.
If you need a test on your data @BayssetGuillaume , please provide me the html and i'll send you equivalent pics.

![image](https://github.com/Dessia-tech/plot_data/assets/106539650/99357306-1d26-45e0-89b6-cb3bd88a22b6)

![image](https://github.com/Dessia-tech/plot_data/assets/106539650/a4812ca0-58eb-441e-9bf6-4f067fe72abf)

2023-06-13 15:07 UTC, GhislainJ requested changes

2023-06-13 15:12 UTC, Tanguylo commented on src/plot-data.ts
> +        const offset = Math.min(axisTitle.width, this.x_step / 2);
Thanks

2023-06-13 15:16 UTC, Tanguylo commented on src/plot-data.ts
> +        axisTitle.format(this.context);
You are pointing out that i did not write a while loop in newText to get the best font size for a given rectangle

2023-06-13 15:17 UTC, Tanguylo commented on src/plot-data.ts
> +        axisTitle.format(this.context);
Same answer ;)

2023-06-13 15:17 UTC, Tanguylo commented on src/plot-data.ts
> +  // public static initialize_click_on_name(nb_axis:number, mouse1X:number, mouse1Y:number, plot_data:any) {
Removed

2023-06-13 15:17 UTC, Tanguylo commented on src/subplots.ts
> +        console.log(data, data.package_version)
Yesssss !

2023-06-13 15:27 UTC, Tanguylo commented on src/plot-data.ts
> +      if (axisTitle.width > (this.axis_x_start - this.X) * 2) {
Called it RIGHT_SPACE

2023-06-13 16:59 UTC, GhislainJ approved these changes

2023-06-14 08:31 UTC, merged