Emit filters without refactor
Dessia-tech/plot_data pull request #394
Opened 2024-07-09 16:36 UTC by GhislainJ

2024-07-11 13:38 UTC, Tanguylo requested changes
Perfect. 
The file interactions.ts just needs a trailing new line

2024-07-11 13:38 UTC, Tanguylo commented on src/interactions.ts
> +export const filterUpdate: Subject<FilterUpdate> = new Subject();
I guess it lacks a trailing new line

2024-07-12 14:11 UTC, GhislainJ commented on src/interactions.ts
> +export const filterUpdate: Subject<FilterUpdate> = new Subject();
Added

2024-07-12 14:43 UTC, Tanguylo approved these changes

2024-07-12 14:43 UTC, merged